# Generated by Django 4.2.30 on 2026-06-06 11:44

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='文档标题')),
                ('file', models.FileField(upload_to=search.models.upload_to, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('txt', 'TXT'), ('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content', models.TextField(blank=True, default='', verbose_name='文档内容')),
                ('indexed', models.BooleanField(default=False, verbose_name='是否已索引')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True, verbose_name='搜索词')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='搜索次数')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='最后搜索时间')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'db_table': 'search_history',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
    ]
